### ISSUE TITLE
Support - Test fra brukeren test-skd

### ISSUE THREAD

**Issue by tommyalmendingentester1** [tommyalmendingen/support-test#107]
Innsendt av ai-dev bruker:
test-skd@ai-dev.brreg.no

Innsendt når:
2022-10-05T09:42:57.0516297Z

Support gjelder:
Altinn

Beskrivelse av supportbehov:
Ja det kan du virkelig lure på

Filvedlegg:
https://test.altinndigital.no

```json payload
    {
	"epost": "aas-talme@ai-dev.no",
	"supportTittel": "Jeg trenger hjelp til helgevasken",
	"supportBeskrivelse": "Altinn"
    }
```

**Comment by tommyalmendingen** [comment]
Saken er løst og kan lukkes.
