### ISSUE TITLE
Support - Dette er en ny fredagssak

### ISSUE THREAD

**Issue by tommyalmendingentester1** [tommyalmendingen/support-test#110]
```json payload
    {
	"epost": "aas-talme@ai-dev.no",
	"supportTittel": "Jeg ønsker å ta helg snart",
	"supportBeskrivelse": ""
    }
```
Innsendt av ai-dev bruker:
aas-talme@ai-dev.no

Innsendt når:
2022-10-07T08:49:27.9849427Z

Support gjelder:

Beskrivelse av supportbehov:
Jeg ønsker å ta helg snart

Filvedlegg:
https://test.altinndigital.no

**Comment by tommyalmendingen** [comment]
Oppdatering på saken

**Comment by tommyalmendingen** [comment]
Ny oppdatering

**Comment by tommyalmendingen** [comment]
Lukker saken med denne kommentaren
