### ISSUE TITLE
Support - Dette er en helt ny sak

### ISSUE THREAD

**Issue by tommyalmendingentester1** [tommyalmendingen/support-test#147]
emailprefill: tommy.almendingen@gmail.com
serviceownerprefill: SKD-Skatteetaten

Innsendt av ai-dev bruker:
aas-talme@ai-dev.no

Innsendt når:
2022-11-03T09:12:06.0490624Z

Support gjelder:
Altinn

Beskrivelse av supportbehov:
Jeg har ingen anelse

Filvedlegg:
https://test.altinndigital.no/contentassets/b96a13a431894c2aa4acffd02c8733b2/uploaded-files/123134796_174077504297892_1669332061392646784_n_638030671244395875.jpg#@123134796_174077504297892_1669332061392646784_n.jpg

**Comment by tommyalmendingen** [comment]
Saken er nå sendt over til leverandør

**Comment by tommyalmendingentester1** [comment]
emailprefill:  

serviceownerprefill: 


Innsendt av ai-dev bruker:
aas-talme@ai-dev.no


Innsendt når:
2022-11-03T09:17:31.1416951Z

Oppdatering på saken:
Dere kan lukke saken for den er fikset


Filvedlegg:
https://test.altinndigital.no
