### ISSUE TITLE
Bestille produksjonssetting

### ISSUE THREAD

**Issue by tommyalmendingen** [tommyalmendingen/support-test#2]
## Deloppgaver som må gjøres
- [x] Deloppgave 1
- [ ] #19
- [ ] Deloppgave 3

**Comment by tommyalmendingentester1** [comment]
Svarer via e-post direkte fra Outlook. (E-posten ble først videresendt fra Gmail og hit).

mvh
Tommy

Fra: Tommy Almendingen ***@***.***>
Sendt: mandag 21. februar 2022 14:08
Til: tommyalmendingen/support-test ***@***.***>
Kopi: tommyalmendingentester1 ***@***.***>; Assign ***@***.***>
Emne: Re: [tommyalmendingen/support-test] Bestille produksjonssetting (Issue #2)


Assigned #2<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Ftommyalmendingen%2Fsupport-test%2Fissues%2F2&data=04%7C01%7C%7Cfb7ab461305243afe5b808d9f53b2457%7C008e560f08af4ceca056b35447503991%7C1%7C0%7C637810456630025889%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=fJN1WfxrIG6VCjN6kTmDq6jvJcvmdQCwCDFtXmDsaRM%3D&reserved=0> to @tommyalmendingentester1<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Ftommyalmendingentester1&data=04%7C01%7C%7Cfb7ab461305243afe5b808d9f53b2457%7C008e560f08af4ceca056b35447503991%7C1%7C0%7C637810456630025889%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=vK9uC3%2BoEA5jl5AegMrQeYJaptmHVRepfrFUmIlYLsQ%3D&reserved=0>.

-
Reply to this email directly, view it on GitHub<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Ftommyalmendingen%2Fsupport-test%2Fissues%2F2%23event-6111472576&data=04%7C01%7C%7Cfb7ab461305243afe5b808d9f53b2457%7C008e560f08af4ceca056b35447503991%7C1%7C0%7C637810456630025889%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=DSPtPL8Fcyt4SYnWZglrfqKU9zJpYufCxoITY6mMCjA%3D&reserved=0>, or unsubscribe<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAX37ZA243HTS54Z3LLFMEYTU4I2JVANCNFSM5O6CCIMA&data=04%7C01%7C%7Cfb7ab461305243afe5b808d9f53b2457%7C008e560f08af4ceca056b35447503991%7C1%7C0%7C637810456630025889%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=xSeA2pJVr%2B6O7MNuUmevMSRb1uCbuBFZ9jVBdZIlN1I%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7C%7Cfb7ab461305243afe5b808d9f53b2457%7C008e560f08af4ceca056b35447503991%7C1%7C0%7C637810456630025889%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=zshj42WOa9%2BdYlr6FQBMcS0Ba2oOo%2FUjbTKxEpR0BWk%3D&reserved=0> or Android<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7C%7Cfb7ab461305243afe5b808d9f53b2457%7C008e560f08af4ceca056b35447503991%7C1%7C0%7C637810456630025889%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=sXRTd%2BCCrxHBNJ3VPniVqNvuXv5HAFlQ4dlgTNgX8bo%3D&reserved=0>.

**Comment by tommyalmendingentester1** [comment]
Svarer her fra Gmail

mvh
Tommy

man. 21. feb. 2022 kl. 14:07 skrev Tommy Almendingen <
***@***.***>:

**Comment by tommyalmendingen** [comment]
Dette er en kommentar lagt inn fra prosjekt view
