### ISSUE TITLE
[48] Support - Har mistet passordet mitt

### ISSUE THREAD

**Issue by tommyalmendingentester1** [tommyalmendingen/support-test#48]
Innsendt av ai-dev bruker:
test-skd@ai-dev.brreg.no

Innsendt når:
2022-03-18T09:14:50.8325858Z

Support gjelder:
Altinn

Beskrivelse av supportbehov:
Har mistet passordet til bilen min.

Filvedlegg:
https://test.altinndigital.no/contentassets/b96a13a431894c2aa4acffd02c8733b2/uploaded-files/2021-05-08_20-02-11_637831952899889308.png#@2021-05-08_20-02-11.png

**Comment by tommyalmendingen** [comment]
Saken er mottatt og oversendt til leverandør

**Comment by tommyalmendingentester1** [comment]
Innsendt av ai-dev bruker:
test-skd@ai-dev.brreg.no


Innsendt når:
2022-03-18T09:17:18.8513425Z

Oppdatering på saken:
Dere kan lukke saken nå for jeg har funnet nøklene mine


Filvedlegg:
https://test.altinndigital.no/contentassets/c4e0857955bf4607b1975b7f85a2d922/uploaded-files/2021-05-08_22-22-46_637831954383044898.png#@2021-05-08_22-22-46.png

**Comment by tommyalmendingen** [comment]
Se vedlegg:

![123313461_175448920827417_371964498414044423_n](https://user-images.githubusercontent.com/45939254/160084683-9d51155a-bbf5-43b6-900f-0eed61d38ad3.jpg)
