### ISSUE TITLE
Support - Trenger mere penger

### ISSUE THREAD

**Issue by tommyalmendingentester1** [tommyalmendingen/support-test#83]
Innsendt av ai-dev bruker:
test-skd@ai-dev.brreg.no

Innsendt når:
2022-05-12T11:07:43.0475024Z

Support gjelder:
Altinn

Beskrivelse av supportbehov:
Noen som har 12 millioner på SD?

- [x] #84
- [ ] 

- [ ] sasafd

Filvedlegg:
https://test.altinndigital.no/contentassets/b96a13a431894c2aa4acffd02c8733b2/uploaded-files/romplan-2.-etasje-pa-salhus_637879576624067910.jpg#@Romplan 2. etasje på Salhus.jpg

**Comment by tommyalmendingentester1** [comment]
Innsendt av ai-dev bruker:
test-skd@ai-dev.brreg.no


Innsendt når:
2022-05-12T11:13:24.6723693Z

Oppdatering på saken:
Har lett og funnet 10 millioner i nattbordskuffen og mangler bare 2


Filvedlegg:
https://test.altinndigital.no

**Comment by tommyalmendingen** [comment]
Vi har funnet to millioner

**Comment by tommyalmendingen** [comment]
[ ] ny sak

**Comment by tommyalmendingen** [comment]
- [ ] sfadsfadsf
- [ ] sadfsadfsfda

**Comment by tommyalmendingentester1** [comment]
Innsendt av ai-dev bruker:
aas-talme@ai-dev.no


Innsendt når:
2022-05-12T12:05:32.8098348Z

Oppdatering på saken:
Fant ikke pengene allikevel


Filvedlegg:
https://test.altinndigital.no

**Comment by DigdirAme** [comment]
Lukker denne.
