### ISSUE TITLE
Support - Anita lurer på så mangt

### ISSUE THREAD

**Issue by tommyalmendingentester1** [tommyalmendingen/support-test#85]
Innsendt av ai-dev bruker:
aas-ameis@ai-dev.no

Innsendt når:
2022-05-12T12:57:32.4613298Z

Support gjelder:
Altinn

Beskrivelse av supportbehov:
Noen som kan bidra?

Filvedlegg:
https://test.altinndigital.no

**Comment by tommyalmendingentester1** [comment]
Innsendt av ai-dev bruker:
aas-ameis@ai-dev.no


Innsendt når:
2022-05-12T13:14:46.9083013Z

Oppdatering på saken:
Trenger hjelp med innlogging Buypass smartkort SEID 2.0


Filvedlegg:
https://test.altinndigital.no/contentassets/800588e23ec8474684fe1db8501a946b/uploaded-files/image002_637879652842479979.png#@image002.png

**Comment by DigdirAme** [comment]
Da er denne saken løst, se vedlegg.
[Kopi av Varslingsmaler.xlsx](https://github.com/tommyalmendingen/support-test/files/8684525/Kopi.av.Varslingsmaler.xlsx)
