### ISSUE TITLE
Support - testing

### ISSUE THREAD

**Issue by tommyalmendingentester1** [tommyalmendingen/support-test#86]
Innsendt av ai-dev bruker:
aas-ghorn@ai-dev.no

Innsendt når:
2022-05-13T06:43:09.7314534Z

Support gjelder:
Altinn

Beskrivelse av supportbehov:
Dette er en test fra Geir H

Filvedlegg:
https://test.altinndigital.no

**Comment by tommyalmendingentester1** [comment]
Innsendt av ai-dev bruker:
aas-ghorn@ai-dev.no


Innsendt når:
2022-05-13T06:46:05.1796065Z

Oppdatering på saken:
Feilen er rettet


Filvedlegg:
https://test.altinndigital.no

**Comment by GeirHerbertHorn** [comment]
fereertert
