### ISSUE TITLE
Support - Ønsker hjelp til å stryke bunadskjorte

### ISSUE THREAD

**Issue by tommyalmendingentester1** [tommyalmendingen/support-test#90]
Innsendt av ai-dev bruker:
aas-ameis@ai-dev.no

Innsendt når:
2022-05-16T08:38:22.3990143Z

Support gjelder:
Altinn

Beskrivelse av supportbehov:
Anyone?

Filvedlegg:
https://test.altinndigital.no/contentassets/b96a13a431894c2aa4acffd02c8733b2/uploaded-files/bestillingsskjema_api_637882943013821959.doc#@Bestillingsskjema_API.doc

**Comment by GeirHerbertHorn** [comment]
Tror ikke dette har noe med oss  gjøre. Hør med Bunadmesteren.
