### ISSUE TITLE
Support - Anita sin testsak

### ISSUE THREAD

**Issue by tommyalmendingentester1** [tommyalmendingen/support-test#92]
Innsendt av ai-dev bruker:
aas-ameis@ai-dev.no

Innsendt når:
2022-05-18T10:06:57.0731401Z

Support gjelder:
Altinn

Beskrivelse av supportbehov:
Hjelp meg!!

Filvedlegg:
https://test.altinndigital.no/contentassets/b96a13a431894c2aa4acffd02c8733b2/uploaded-files/testing-github_637884724143000811.docx#@Testing GitHub.docx

**Comment by DigdirAme** [comment]
Hva trenger du hjelp til?

**Comment by tommyalmendingentester1** [comment]
Innsendt av ai-dev bruker:
aas-ameis@ai-dev.no


Innsendt når:
2022-05-18T10:09:51.7695471Z

Oppdatering på saken:
Trenger hjelp til å logge inn på altinn.


Filvedlegg:
https://test.altinndigital.no/contentassets/800588e23ec8474684fe1db8501a946b/uploaded-files/bestillingsskjema_api_637884725911432761.doc#@Bestillingsskjema_API.doc

**Comment by DigdirAme** [comment]
<img width="626" alt="image" src="https://user-images.githubusercontent.com/94672791/169020272-8f955cd7-73c6-4995-a3c0-808eae18f558.png">

**Comment by DigdirAme** [comment]
Lukker denne.

**Comment by tommyalmendingentester1** [comment]
Innsendt av ai-dev bruker:
aas-ameis@ai-dev.no


Innsendt når:
2022-05-18T10:42:40.7494695Z

Oppdatering på saken:
Ikke enig


Filvedlegg:
https://test.altinndigital.no
